mvn -Pdataflow-runner compile exec:java \
      -Dexec.mainClass=com.tailoredbrands.pipeline.pattern.jms_to_pub_sub.JmsToPubSubStreamingPipeline \
      -Dexec.args="--project=tst1-integration-3ca6 \
      --region=us-east1 \
      --gcpTempLocation=gs://tst1-integration-3ca6-jms-pubsub-df-temp/temp/ \
      --stagingLocation=gs://tst1-integration-3ca6-jms-pubsub-df-staging/staging/ \
      --serviceAccount=project-service-account@tst1-integration-3ca6.iam.gserviceaccount.com \
      --subnetwork=https://www.googleapis.com/compute/v1/projects/network-b2b9/regions/us-east1/subnetworks/np-integration4 \
      --jmsCredentialsSecret=secret_item_delta_feed \
      --jmsProvider=tibco \
      --jmsServerUrl=mqhatstsubcorp.tmw.com \
      --jmsQueue=GOOGLE.CLOUD.PUBLISHER \
      --outputPubsubTopic=projects/tst1-integration-3ca6/topics/item_delta_feed \
      --deadletterPubsubTopic=projects/tst1-integration-3ca6/topics/deadletter \
      --businessInterface=item_delta_feed \
      --patternFullName=item_delta_feed \
      --tbUser=admin@tbi.com \
      --autoscalingAlgorithm=THROUGHPUT_BASED \
      --workerMachineType=n1-standard-2 \
      --enableStreamingEngine=true \
      --maxNumWorkers=10 \
      --runner=DataflowRunner"