name: Retail Deploy Greetings Cloud Function
on:
  push:
    branches: [ master ]
    paths:
      - app1/**
env:
  PROJECT: essex-retail
  SA: project-service-account@essex-retail.iam.gserviceaccount.com
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_RETAIL_SA }}
          
      - name: Setup Apine Retail GCP Service Account
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{env.PROJECT}}

      - name: deploy cloud function
        run:  |
          gcloud functions deploy App1 \
          --gen2 \
          --region=${{env.REGION}} \
          --runtime=java17 \
          --source=$PWD/app1 \
          --entry-point=com.google.cloud.GreetingsHTTPApplication \
          --service-account=${{env.SA}} \
          --trigger-http \
          --allow-unauthenticated \
          --serve-all-traffic-latest-revision 

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding App1 --member="allUsers" --role="roles/cloudfunctions.invoker"

