name: Retail Deploy Greetings Cloud Function
on:
  push:
    branches: [ master ]
env:
  PROJECT: essex-retail
  SA: project-service-account@essex-retail.iam.gserviceaccount.com
  REGION: us-central1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_RETAIL_SA }}
          
      - name: Setup Apine Retail GCP Service Account
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{env.PROJECT}}

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: GreetingsHTTPApplication
          runtime: java17
          project_id: ${{env.PROJECT}}
          entry_point: com.google.cloud.GreetingsHTTPApplication
          region: ${{env.REGION}}
          build_service_account: projects/${{env.PROJECT}}/serviceAccounts/${{env.SA}}
          service_account: ${{env.SA}}
          ingress_settings: ALLOW_ALL
          all_traffic_on_latest_revision: true

      - name: make the url aunthenticated
        run: |
          gcloud functions add-iam-policy-binding GreetingsHTTPApplication --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: curl "${{ steps.deploy.outputs.url }}"

